### ISSUE TITLE
Outcome?

### ISSUE THREAD

**Issue by JosXa** [alexdown/rethinkdb-view#1]
Just stumbled over this repo via a google search. I think after 6 years it's safe to say that most of the README is outdated - would be awesome to have some kind of closure on what's the recommended approach to get something similar to views using RethinkDB in 2021 :)
MongoDB does have proper change streams now for example, it's not considered a hack anymore

**Comment by alexdown** [comment]
hi @JosXa - indeed after 6 years I won't trust the README to be up to date.. :)

I created this example together with [this other one](https://github.com/alexdown/mongo-view), mostly to support a [feature request](https://jira.mongodb.org/browse/SERVER-142) for mongo to introduce views. Kinda like "_see? you're so backwards, even RethinkDB supports that without hackety hacks. please do what I need_ 😜".

I didn't have a chance to use RethinkDB for a real product at the end (we went for postgre), so I don't really have real life experience to share nor I am up to date on RethinkDB features... 
that said, if you are, and want to send a PR, I'll happily approve!

thanks for starting my 2021 with a blast from the past :)

**Comment by JosXa** [comment]
> thanks for starting my 2021 with a blast from the past :)

Haha, not sure if sarcasm or honestly happy 😇😝

Alright, looks like RethinkDb went to being a project under community support so maybe it's not such a bad idea to build something with it (I haven't really stood up anything in production yet either).
That said, if I need the views let me maybe make a PR if I figure it out ;D

Happy 2021

**Comment by alexdown** [comment]
> Haha, not sure if sarcasm or honestly happy 😇😝

honestly happy! 😇
